using MelonLoader;
using ModThatIsNotMod.BoneMenu;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Jevil.Prefs;

/// <summary>
/// Class containing references to a MelonPreferences category and BoneMenu MenuCategory.
/// <para>Generated by <see cref="Preferences.Register{T}"/></para>
/// </summary>
public record PrefEntries(MelonPreferences_Category MelonPrefsCategory, MenuCategory BoneMenuCategory);
