using MelonLoader;
using ModThatIsNotMod.BoneMenu;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Jevil.Prefs;

/// <summary>
/// Class containing references to a MelonPreferences category and BoneMenu MenuCategory.
/// <para>Generated by <see cref="Preferences.Register{T}"/></para>
/// </summary>
public class PrefEntries
{
    /// <summary>
    /// can you read?
    /// </summary>
    public readonly MelonPreferences_Category melonPrefsCategory;
    /// <summary>
    /// https://media.discordapp.net/attachments/892903039432785922/951904926139830302/throwit-1.gif
    /// </summary>
    public readonly MenuCategory bmMenuCategory;

    internal PrefEntries(MelonPreferences_Category mpCat, MenuCategory bmCat)
    {
        /* "mpCat", "bmCat"
         *   /\______/\
         *  /  ^    ^  \
         *  |    <>    |
         *  \  \_/\_/  /
         *   \________/
         */

        melonPrefsCategory = mpCat;
        bmMenuCategory = bmCat;
    }
}
