using MelonLoader;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Jevil.Prefs;

/// <summary>
/// Class containing references to a MelonPreferences category and BoneMenu MenuCategory.
/// todo: add BoneLib menu category
/// <para>Generated by <see cref="Preferences.Register{T}"/></para>
/// </summary>
public sealed record PrefEntries(MelonPreferences_Category MelonPrefsCategory);
